// 应用中心相关权限
export default {
    // 应用相关权限
    AdminApplicationCenterApplicationRead: 'Admin::ApplicationCenter_Application::Read',
    AdminApplicationCenterApplicationOperate: 'Admin::ApplicationCenter_Application::Operate',
    AdminApplicationCenterApplicationQuotaManage: 'Admin::ApplicationCenter_Application::QuotaManage',
    AdminApplicationCenterApplicationMaintain: 'Admin::ApplicationCenter_Application::Maintain',
    AdminApplicationCenterApplicationResourceManage: 'Admin::ApplicationCenter_Application::ResourceManage',
    // 应用包
    AdminApplicationCenterApplicationPackageRead: 'Admin::ApplicationCenter_ApplicationPackage::Read',
    AdminApplicationCenterApplicationPackageOperate: 'Admin::ApplicationCenter_ApplicationPackage::Operate',
    AdminApplicationCenterApplicationPackageMaintain: 'Admin::ApplicationCenter_ApplicationPackage::Maintain',
    AdminApplicationCenterApplicationPackageVersionOperate: 'Admin::ApplicationCenter_ApplicationPackageVersion::Operate',
    // 应用商店
    AdminApplicationCenterApplicationCenterRead: 'Admin::ApplicationCenter_ApplicationCenter::Read',
    AdminApplicationCenterApplicationCenterApplicationCreate: 'Admin::ApplicationCenter_ApplicationCenter::ApplicationCreate',
    AdminApplicationCenterApplicationCenterOperate: 'Admin::ApplicationCenter_ApplicationCenter::Operate',
    // 节点
    AdminApplicationCenterNodeResourceRead: 'Admin::ApplicationCenter_NodeResource::Read',
    AdminApplicationCenterNodeResourceOperate: 'Admin::ApplicationCenter_NodeResource::Operate',
    // 持久存储卷
    AdminApplicationCenterStorageResourceRead: 'Admin::ApplicationCenter_StorageResource::Read',
    // 网络资源
    AdminApplicationCenterNetworkResourceRead: 'Admin::ApplicationCenter_NetworkResource::Read',
    // 资源对象类型
    AdminApplicationCenterResourceObjectTypeRead: 'Admin::ApplicationCenter_ResourceObjectType::Read',
    AdminApplicationCenterResourceObjectTypeOperate: 'Admin::ApplicationCenter_ResourceObjectType::Operate',
    // 容器
    AdminApplicationCenterContainerRead: 'Admin::ApplicationCenter_Container::Read',
    AdminApplicationCenterContainerOperate: 'Admin::ApplicationCenter_Container::Operate',
    // 平台公共库镜像
    AdminApplicationCenterImagePublicImageRead: 'Admin::ApplicationCenter_Image_PublicImage::Read',
    // 公共库镜像
    AdminApplicationCenterImagePublicImageOperate: 'Admin::ApplicationCenter_Image_PublicImage::Operate',
    // 应用商店库镜像
    AdminApplicationCenterImageCenterImageRead: 'Admin::ApplicationCenter_Image_CenterImage::Read',
    // 项目库镜像查看
    AdminApplicationCenterImagePrivateImageRead: 'Admin::ApplicationCenter_Image_PrivateImage::Read',
    // 项目库镜像管理
    AdminApplicationCenterImagePrivateImageOperate: 'Admin::ApplicationCenter_Image_PrivateImage::Operate',
    // 项目库初始化
    AdminApplicationCenterImagePrivateRepoOperate: 'Admin::ApplicationCenter_Image_PrivateRepo::Operate',
    // 镜像凭证查看
    AdminApplicationCenterCredentialRead: 'Admin::ApplicationCenter_Credential::Read',
    // 系统凭证管理
    AdminApplicationCenterCredentialSystemOperate: 'Admin::ApplicationCenter_Credential_System::Operate',
    // 项目凭证管理
    AdminApplicationCenterCredentialPorjectOperate: 'Admin::ApplicationCenter_Credential_Porject::Operate'

}