FROM harbor.huayun.org/library/nginx:1.21.0_mips64le

ARG DIST_PATH=/opt/haihe/tmp_front/application/

RUN mkdir -p $DIST_PATH

COPY dist $DIST_PATH

CMD ["cp", "-r", "/opt/haihe/tmp_front/application/*", "/opt/haihe/front/application/"]
